formatter: "markdown table" # this is required
sections:
  show: 
    - inputs
    - outputs
    - providers
    - modules
    - resources

output:
  file: "README.md"

content: |-
  <p align="center">
    <img width="200" height="200" src="docs/terraform-icon.svg"><br>
    <h1 align="center">Terraform Infrastructure Documentation</h1>
  </p>

  {{ .Inputs }}
  {{ .Resources }} 
  {{ .Outputs }}
  {{ .Providers }}
  {{ .Modules }}
  
