name: "Deploy Production Environment"

on:
  release:
    types: [released]
  
jobs: 
 apply_production:
    name: Apply Production Environment
    runs-on: ubuntu-latest
    concurrency:
      group: production
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::225079546399:role/alix-dev-github-actions
          aws-region: us-east-1
          mask-aws-account-id: false
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        env: 
          TF_WORKSPACE: production
          TF_VAR_whitelist_enabled: false
          TF_VAR_dd_api_key: ${{ secrets.DD_API_KEY }}
          TF_VAR_slack_webhook_url:  ${{ secrets.SLACK_WEBHOOK_URL }}
        run: terraform apply -no-color --auto-approve
        continue-on-error: false

      - name: Upload VPN Profiles
        id: vpn-profiles
        env: 
          bucket: alix-terraform
          vpn_directory: ovpn
        run: aws s3 cp --acl bucket-owner-full-control --recursive ${{ env.vpn_directory }}/. s3://${{ env.bucket }}/vpn/production/

